default: &default
  TWILIO_SID: 'AC159ea454d65ec3c5d443d7da8d4b5644'
  TWILIO_TOKEN: '301b4fd074ff17b541a42962725bab3c'
  TWILIO_NUMBER: '+16467599030'
  WIT_TOKEN: 'U2TCQ2PH5BEPVEZEBQASZSNGI6FIN7ML'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default