default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  host: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: meetable_development


test:
  <<: *default
  database: meetable_test